<a href="https://colab.research.google.com/github/abdmuiz1510/data-science-toolkit/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as nump

1. Create a numpy array of size 2 x 2

In [8]:
array = nump.array([[1,2],[4,5]])
print (array)

[[1 2]
 [4 5]]


2. Create a random numpy array of size 3 x 4

In [12]:
array2 = nump.random.rand(3,4)
print (array2)

[[0.52644934 0.9775824  0.51938228 0.86409788]
 [0.13911485 0.16143923 0.81402906 0.22736969]
 [0.9843294  0.85759645 0.76971999 0.95687394]]


3. Create a numpy array of ones and a numpy array of zeroes

In [14]:
array_ones = nump.ones((2,2))
array_zeros = nump.zeros((2,2))

print ("Array of ones : \n ", array_ones)
print ("Array of zeros : \n ", array_zeros)

Array of ones : 
  [[1. 1.]
 [1. 1.]]
Array of zeros : 
  [[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [21]:
random_array = nump.random.randint(1,100,(6,3))
print ("Original array 6x3 : \n", random_array)
print ("\n")
print ("Transpose array 6x3 : \n", random_array.T)


Original array 6x3 : 
 [[68 92 20]
 [58 30 11]
 [51 84 67]
 [88 26 22]
 [64 29 44]
 [76 37 65]]


Transpose array 6x3 : 
 [[68 58 51 88 64 76]
 [92 30 84 26 29 37]
 [20 11 67 22 44 65]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [24]:
# n=2, p=3, m=4

M = nump.random.randint(1,50,(2,3))
Z = nump.random.randint(1,50,(3,4))

print ("Array n x p : \n", M)
print ("\n")
print ("Array m x p : \n", Z)

dot_product = nump.dot(M,Z)

print ("\n'")
print ("Dot product : \n", dot_product)

Array n x p : 
 [[ 3 20 19]
 [10 15  7]]


Array m x p : 
 [[28 45 43 44]
 [40 32 15 32]
 [39  5 26 19]]

'
Dot product : 
 [[1625  870  923 1133]
 [1153  965  837 1053]]
